---
abstract: 'text utilities for GD'
author:
  - 'Martien Verbruggen (mgjv@comdyn.com.au)'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: GDTextUtil
no_index:
  directory:
    - t
    - inc
requires:
  GD: '1'
version: '0.86'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
